import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavPrincipal from "@/components/NavPrincipal";
import BarraUsuario from "@/components/BarraUsuario";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mi bitácora",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavPrincipal />
        <BarraUsuario />
        {children}
      </body>
    </html>
  );
}
